### ISSUE TITLE
Remove information from data.yml and add multiple .md files 

### ISSUE THREAD

**Issue by reeceawalsh** [NewcastleRSE/sweet-project-website#20]
The current dev branch has all of the information on the site in a data.yml and has conditional rendering based on the type of content being rendered. 

```
programme:
  programme:
  title: About the programme
  content:
    - description:
        - type: paragraph
          text: The SWEET research programme will develop and investigate the effectiveness of a blended intervention (HT&Me) to support adherence to hormone therapy and improve quality of life for women with early breast cancer.
        - type: paragraph
          text: "The intervention includes:"
        - type: list
          items:
            - A short animation video providing information on how hormone therapy works, why it is important to take daily, and advice for managing side-effects
            - Two appointments with HT&Me study nurses
            - Access to the interactive HT&Me website
            - Regular text/email messages reminding of the importance of hormone therapy and signposting back to the HT&Me website
      img: /assets/images/Programme1.png
    - description:
        - type: paragraph
          text: The programme includes five workstreams, as shown below.
      img: /assets/images/Programme2.png
```

This is fine for editing information, but may cause problems when the client wants to add things, in which case markup would be better. The project structure needs a full rework and to use multiple .md files instead. This will require an overhaul of the html files also.
